use Mail::Sender;
use DateTime;
use strict;
use warnings;
use Parallel::ForkManager;

my @browser = ('*firefox','*iexplore');
my $i= @browser;

my $pm = new Parallel::ForkManager($i);
my $pid;
my $browser;

foreach $browser (@browser){

$pid =  $pm->start and next;

if($pid == 0){

my $dt = DateTime->now( time_zone  => 'local',);

my $filename_fs = "Results\\Results_".$dt->ymd('_')."_".$dt->hour()."_".$dt->minute()."_".$dt->second().".txt";  

my $host = 'mx.valuelabs.net';

my $displayname = 'Automation';

my $to = 'madhubabu.garlapati';

my $cc = 'madhubabu.garlapati1';

my $subject = 'Automated Test Case Summary';

my $msgbody = "Hi All,<br><br> Please find the status of the Automated Test Summary in the following Attachment.<br>";
$msgbody = $msgbody."<br>Thanks, <br><b>Automation Team</b><br><br><b>Note</b>:This is an automated Email generated by Selenium.";
$msgbody = $msgbody."All failed cases would be re-executed manually to verify if they are really build error(s) and not Test Data/Script errors";


my $cmd = "prove -vm t/D.t :: .testrc > $filename_fs";
#$cmd = "date/?  > $filename_fs";
my $output = qx($cmd);

my $sender = new Mail::Sender{smtp => $host, from => $displayname."\@valuelabs.net"};
$sender->MailFile({to => $to ,cc=>$cc,subject => $subject,msg =>$msgbody,file =>$filename_fs, ctype=>'text/html'});

$output = qx("type $filename_fs");
if ($output =~ /Result: PASS/) {
exit 0;
}
else{
exit 1;
}

$pm->finish();
}
}


